import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const mainFont = Poppins({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-poppins',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${mainFont.variable} font-sans bg-white`}>
				<div className="max-w-[1200px] w-full mx-auto">{children}</div>
			</body>
		</html>
	)
}
